[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gpt-from-scratch"
version = "0.1.0"
description = "GPT from stratch."
readme = "README.md"
requires-python = ">=3.8"
authors = [
  {name = "Muhammed Yıldız"}
]
dependencies = [
    "torch",
    "matplotlib",
    "numpy"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
